config/routes.rb
Rails.application.routes.draw do
  # Root
  root to: "homepage#index"

  # API Site
  constraints subdomain: 'api' do
    mount Twitter::Root => '/'

    unless Rails.env.production?
      mount GrapeSwaggerRails::Engine => '/:version/docs'
    end
  end

  # Users Site
  devise_for :users
  namespace :users do
    root to: "users#index"
  end

  # Admins Site
  devise_for :admins
  namespace :admins do
    root to: "admins#index"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  #
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  layout :layout_by_resource

  private

  def layout_by_resource
    if devise_controller? && resource_name == :admin
      'admins'
    else
      'users'
    end
  end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/homepage/index.html.erb
<div style="width:100%;height:100%;text-align:center;margin-top:7em; background-color:white;">
  <%= link_to 'User', user_session_path %>
  <%= link_to 'Admin', admin_session_path %>
</div>

app/views/layouts/admins.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Admin Site</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Simple Rails Website</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/users.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>User Site</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>